<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Vets database menu system</title>
        <style>
        body {
            margin:0;
        }
        .menu, footer {
            background:blue;
            color:white;
            font-size:large;
            font-family:Courier;
        }
        .menu a {
            margin:1em;
            border: 1px solid red;
            background-color:yellow;
            color:black;
            text-decoration:none;
        }
        footer {
            text-align:center;
            font-size:smaller;
        }
        </style>
    </head>
    <body>

<!--#include file="menu.inc"-->